kevin/footer
acm-ucr/ewb-website pull request #53
Opened 2023-10-27 22:06 UTC by Kevinloritsch

2023-10-27 22:15 UTC, Kevinloritsch commented
![image](https://github.com/acm-ucr/ewb-website/assets/56408094/90cc443c-937b-4d6a-ab39-916514f61c89)

2023-11-03 06:17 UTC, menthy-wu commented on src/components/Footer.jsx
> +        <br />
instead of br, use patting top in classname

2023-11-03 06:17 UTC, menthy-wu commented on src/components/Footer.jsx
> +      <div className="w-full bg-ewb-blue-200 border-t-8 border-ewb-green">
make this the parent component.
think of the entire footer as two parts: the logo at the left and the information at the right. You can add a "flex justify-between at the parent component

2023-11-03 06:18 UTC, menthy-wu requested changes

2023-11-03 06:18 UTC, menthy-wu commented on src/components/Footer.jsx
> +        <table className="w-full">
try use the justify-between instead of table

2023-11-03 06:18 UTC, menthy-wu commented on src/components/Footer.jsx
> +                  <div className="inline-flex">
reduce the amount of div wrappers, you can put all classNames in one div

2023-11-03 17:41 UTC, Kevinloritsch commented
![image](https://github.com/acm-ucr/ewb-website/assets/56408094/d3f46d67-73e6-40e1-b2e3-c54adec68064)

2023-11-03 21:27 UTC, menthy-wu requested changes

2023-11-03 21:27 UTC, menthy-wu commented on src/components/Footer.jsx
> +    <div className="w-full bg-ewb-green">
remove this div

2023-11-03 21:27 UTC, menthy-wu commented on src/components/Footer.jsx
> +      <div className="w-full bg-ewb-blue-200 border-t-8 border-t-ewb-green pt-32 flex justify-between">
border-t-[20px]

2023-11-03 21:27 UTC, menthy-wu commented on src/components/Footer.jsx
> +            {" "}
remove {" "}

2023-11-03 21:34 UTC, Kevinloritsch commented
![image](https://github.com/acm-ucr/ewb-website/assets/56408094/b7869ac0-c27b-41ad-839f-1320cd220866)

2023-11-03 21:39 UTC, menthy-wu requested changes

2023-11-03 21:39 UTC, menthy-wu commented on src/components/Footer.jsx
> +        <div className="ml-3 scale-125 float-right">{ICONS["facebook"]}</div>
make it a link https://github.com/acm-ucr/ewb-website/blob/dev/src/components/home/Social.jsx

2023-11-03 22:28 UTC, Kevinloritsch commented
![image](https://github.com/acm-ucr/ewb-website/assets/56408094/d8da2706-a1b0-4bb6-978d-6c247f326ff0)

Added link functionality.

2023-11-04 00:40 UTC, menthy-wu approved these changes

2023-11-04 00:48 UTC, merged