Fuyuki/Mobile-Responsiveness-Event
acm-ucr/ewb-website pull request #66
Opened 2023-11-06 05:24 UTC by Fuyuki325

Potentially Fixed Mobile Responsive Event #62

![Mobile-Event1](https://github.com/acm-ucr/ewb-website/assets/120443522/17fe204b-2499-4066-99ab-18f78cd615db)

2023-11-08 17:48 UTC, menthy-wu requested changes

2023-11-08 17:48 UTC, menthy-wu commented on src/components/home/Event.jsx
> -        <div className="text-base font-normal">{descripton}</div>
keep it base in a bigger screen. so you can do something like "text-sm md:text-base" so the text will be small on small screen and be base on screen lager than middle

2023-11-08 17:48 UTC, menthy-wu commented on src/components/home/Event.jsx
> -        className={`text-4xl text-white text-center w-1/6 aspect-square flex flex-col items-center justify-center ${COLORS[color].bg}`}
use breakpoint like "w-1/2 md: w-1/6" so the with will remain 1/6 on screen larger than md and it will be 1/2 on small screen

2023-11-09 23:52 UTC, Fuyuki325 commented
Added breakpoints for the description and the colored div
![Mobile-Event1](https://github.com/acm-ucr/ewb-website/assets/120443522/46f10811-ccf9-4d59-9b5e-957916de5f5d)

2023-11-11 09:06 UTC, menthy-wu approved these changes

2023-11-11 09:07 UTC, merged